name: StudySync Cloud CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # Install Docker Compose
      # =========================
      - name: Check Docker
        run: docker --version

      # =========================
      # Build StudySync
      # =========================
      - name: Build StudySync
        run: |
          cd StudySync
          docker compose build

      # =========================
      # Build CloudStorageServer
      # =========================
      - name: Build Cloud Storage Server
        run: |
          cd CloudStorageServer
          docker compose build