name: StudySync Cloud CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # STUDYSYNC BUILD
      # =========================

      - name: Build StudySync
        working-directory: ./StudySync
        run: docker compose build

      # =========================
      # STORAGE SERVER BUILD
      # =========================

      - name: Build Storage Server
        working-directory: ./CloudStorageServer
        run: docker compose build

      # =========================
      # SUCCESS MESSAGE
      # =========================

      - name: CI Passed
        run: echo "StudySync CI/CD pipeline successful!"